# Generated by Django 2.1.1 on 2018-09-29 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, default='', max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('birth_year', models.SmallIntegerField(blank=True, default=0)),
                ('death_year', models.SmallIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_text', models.TextField()),
                ('date_added', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateField(blank=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'book')], default=1)),
                ('authors', models.ManyToManyField(to='snippets.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('code', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='snippets.Source'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='snippets.Tag'),
        ),
    ]
