# Generated by Django 2.1.1 on 2018-09-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_text',
            new_name='text',
        ),
    ]
