# Generated by Django 2.1.2 on 2018-10-02 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180929_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeTransferStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('transferred', 'Transferred'), ('in progress', 'In Progress'), ('not started', 'Not Started'), ('stalled', 'Stalled')], default='transferred', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('now reading', 'Now reading'), ('read', 'Read'), ('stalled', 'Stalled'), ('to read', 'To Read')], default='now reading', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='snippet',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippets.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='authors',
            field=models.ManyToManyField(related_name='all_work', to='snippets.Author'),
        ),
        migrations.AddField(
            model_name='readingstatus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Source'),
        ),
        migrations.AddField(
            model_name='knowledgetransferstatus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Source'),
        ),
        migrations.AddField(
            model_name='indexentry',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='snippets.Source'),
        ),
        migrations.AddField(
            model_name='indexentry',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippets.Tag'),
        ),
    ]
