# Generated by Django 2.1.2 on 2018-10-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20181002_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='tags',
            field=models.ManyToManyField(to='snippets.Tag'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_snippets', to='snippets.Tag'),
        ),
    ]
