# Generated by Django 2.1.2 on 2018-10-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20181002_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='date_published',
            field=models.DateField(null=True),
        ),
    ]
